import { useState, useEffect, useRef } from "react";
import { THREE } from "expo-three";
import * as FileSystem from "expo-file-system";
import * as MediaLibrary from "expo-media-library";
import * as Sharing from "expo-sharing";

import { Mesh } from "../stores/scanStore";
import { useModelStore } from "../stores/modelStore";

interface UseMeshProcessingProps {
  onExportComplete?: (exportPath: string) => void;
  onError?: (error: string) => void;
}

export function useMeshProcessing({
  onExportComplete,
  onError,
}: UseMeshProcessingProps = {}) {
  const { saveModel } = useModelStore();

  const [isProcessing, setIsProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [exportFormat, setExportFormat] = useState<"obj" | "stl" | "glb">(
    "obj"
  );

  const saveMeshToLibrary = async (
    mesh: Mesh,
    thumbnailUri?: string
  ): Promise<string | null> => {
    setIsProcessing(true);
    setProgress(0);

    try {
      setProgress(30);
      const modelId = await saveModel(mesh, thumbnailUri);
      setProgress(100);
      return modelId;
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Failed to save mesh";
      onError?.(errorMessage);
      return null;
    } finally {
      setIsProcessing(false);
    }
  };

  const exportMesh = async (
    mesh: Mesh,
    format: "obj" | "stl" | "glb" = "obj"
  ): Promise<string | null> => {
    setIsProcessing(true);
    setProgress(0);
    setExportFormat(format);

    try {
      setProgress(20);

      let exportData: string;
      let fileExtension: string;

      switch (format) {
        case "obj":
          exportData = convertToOBJ(mesh);
          fileExtension = "obj";
          break;
        case "stl":
          exportData = convertToSTL(mesh);
          fileExtension = "stl";
          break;
        case "glb":
          exportData = await convertToGLB(mesh);
          fileExtension = "glb";
          break;
        default:
          throw new Error(`Unsupported export format: ${format}`);
      }

      setProgress(70);

      const fileName = `scan_${Date.now()}.${fileExtension}`;
      const fileUri = `${FileSystem.documentDirectory}${fileName}`;

      await FileSystem.writeAsStringAsync(fileUri, exportData, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      setProgress(90);

      const { status } = await MediaLibrary.requestPermissionsAsync();

      if (status === "granted") {
        await MediaLibrary.createAssetAsync(fileUri);
      }

      setProgress(100);
      onExportComplete?.(fileUri);

      return fileUri;
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Failed to export mesh";
      onError?.(errorMessage);
      return null;
    } finally {
      setIsProcessing(false);
    }
  };

  const shareMesh = async (
    mesh: Mesh,
    format: "obj" | "stl" | "glb" = "obj"
  ): Promise<void> => {
    try {
      const exportPath = await exportMesh(mesh, format);

      if (!exportPath) return;

      const canShare = await Sharing.isAvailableAsync();

      if (canShare) {
        await Sharing.shareAsync(exportPath);
      } else {
        onError?.("Sharing is not available on this device");
      }
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Failed to share mesh";
      onError?.(errorMessage);
    }
  };

  const convertToOBJ = (mesh: Mesh): string => {
    let objContent = "# Generated by 3D Space Scanner\n";

    // Add vertices
    for (let i = 0; i < mesh.vertices.length; i += 3) {
      objContent += `v ${mesh.vertices[i]} ${mesh.vertices[i + 1]} ${
        mesh.vertices[i + 2]
      }\n`;
    }

    // Add normals if they exist
    if (mesh.normals) {
      for (let i = 0; i < mesh.normals.length; i += 3) {
        objContent += `vn ${mesh.normals[i]} ${mesh.normals[i + 1]} ${
          mesh.normals[i + 2]
        }\n`;
      }
    }

    // Add texture coordinates if they exist
    if (mesh.uvs) {
      for (let i = 0; i < mesh.uvs.length; i += 2) {
        objContent += `vt ${mesh.uvs[i]} ${mesh.uvs[i + 1]}\n`;
      }
    }

    // Add faces
    for (let i = 0; i < mesh.faces.length; i += 3) {
      const v1 = mesh.faces[i] + 1;
      const v2 = mesh.faces[i + 1] + 1;
      const v3 = mesh.faces[i + 2] + 1;

      if (mesh.normals && mesh.uvs) {
        objContent += `f ${v1}/${v1}/${v1} ${v2}/${v2}/${v2} ${v3}/${v3}/${v3}\n`;
      } else if (mesh.normals) {
        objContent += `f ${v1}//${v1} ${v2}//${v2} ${v3}//${v3}\n`;
      } else if (mesh.uvs) {
        objContent += `f ${v1}/${v1} ${v2}/${v2} ${v3}/${v3}\n`;
      } else {
        objContent += `f ${v1} ${v2} ${v3}\n`;
      }
    }

    return objContent;
  };

  const convertToSTL = (mesh: Mesh): string => {
    let stlContent = "solid 3DScannerMesh\n";

    // Loop through faces
    for (let i = 0; i < mesh.faces.length; i += 3) {
      const i1 = mesh.faces[i] * 3;
      const i2 = mesh.faces[i + 1] * 3;
      const i3 = mesh.faces[i + 2] * 3;

      const v1 = new THREE.Vector3(
        mesh.vertices[i1],
        mesh.vertices[i1 + 1],
        mesh.vertices[i1 + 2]
      );

      const v2 = new THREE.Vector3(
        mesh.vertices[i2],
        mesh.vertices[i2 + 1],
        mesh.vertices[i2 + 2]
      );

      const v3 = new THREE.Vector3(
        mesh.vertices[i3],
        mesh.vertices[i3 + 1],
        mesh.vertices[i3 + 2]
      );

      // Calculate normal
      const normal = new THREE.Vector3()
        .crossVectors(
          new THREE.Vector3().subVectors(v2, v1),
          new THREE.Vector3().subVectors(v3, v1)
        )
        .normalize();

      // Add facet
      stlContent += `  facet normal ${normal.x} ${normal.y} ${normal.z}\n`;
      stlContent += "    outer loop\n";
      stlContent += `      vertex ${v1.x} ${v1.y} ${v1.z}\n`;
      stlContent += `      vertex ${v2.x} ${v2.y} ${v2.z}\n`;
      stlContent += `      vertex ${v3.x} ${v3.y} ${v3.z}\n`;
      stlContent += "    endloop\n";
      stlContent += "  endfacet\n";
    }

    stlContent += "endsolid 3DScannerMesh\n";

    return stlContent;
  };

  const convertToGLB = async (mesh: Mesh): Promise<string> => {
    // This would normally use Three.js GLTFExporter
    // For this example, we'll just return a simplified JSON representation
    const glbData = JSON.stringify({
      asset: {
        version: "2.0",
        generator: "3D Space Scanner",
      },
      scene: 0,
      scenes: [{ nodes: [0] }],
      nodes: [{ mesh: 0 }],
      meshes: [
        {
          primitives: [
            {
              attributes: {
                POSITION: 1,
                NORMAL: mesh.normals ? 2 : undefined,
                TEXCOORD_0: mesh.uvs ? 3 : undefined,
              },
              indices: 0,
              mode: 4,
            },
          ],
        },
      ],
      accessors: [
        {
          bufferView: 0,
          componentType: 5125,
          count: mesh.faces.length,
          type: "SCALAR",
        },
        {
          bufferView: 1,
          componentType: 5126,
          count: mesh.vertices.length / 3,
          type: "VEC3",
          min: [0, 0, 0],
          max: [1, 1, 1],
        },
        mesh.normals
          ? {
              bufferView: 2,
              componentType: 5126,
              count: mesh.normals.length / 3,
              type: "VEC3",
            }
          : null,
        mesh.uvs
          ? {
              bufferView: 3,
              componentType: 5126,
              count: mesh.uvs.length / 2,
              type: "VEC2",
            }
          : null,
      ].filter(Boolean),
      bufferViews: [
        {
          buffer: 0,
          byteOffset: 0,
          byteLength: mesh.faces.length * 4,
          target: 34963,
        },
        {
          buffer: 0,
          byteOffset: mesh.faces.length * 4,
          byteLength: mesh.vertices.length * 4,
          target: 34962,
        },
        mesh.normals
          ? {
              buffer: 0,
              byteOffset: mesh.faces.length * 4 + mesh.vertices.length * 4,
              byteLength: mesh.normals.length * 4,
              target: 34962,
            }
          : null,
        mesh.uvs
          ? {
              buffer: 0,
              byteOffset:
                mesh.faces.length * 4 +
                mesh.vertices.length * 4 +
                (mesh.normals ? mesh.normals.length * 4 : 0),
              byteLength: mesh.uvs.length * 4,
              target: 34962,
            }
          : null,
      ].filter(Boolean),
      buffers: [
        {
          byteLength:
            mesh.faces.length * 4 +
            mesh.vertices.length * 4 +
            (mesh.normals ? mesh.normals.length * 4 : 0) +
            (mesh.uvs ? mesh.uvs.length * 4 : 0),
        },
      ],
    });

    // In a real implementation, we'd convert this JSON to binary GLB
    // For this example, we'll return the JSON as a string
    return glbData;
  };

  const optimizeMesh = (
    mesh: Mesh,
    quality: "low" | "medium" | "high"
  ): Promise<Mesh> => {
    return new Promise((resolve) => {
      setIsProcessing(true);

      // Simulate optimization process
      let progress = 0;
      const interval = setInterval(() => {
        progress += 10;
        setProgress(progress);

        if (progress >= 100) {
          clearInterval(interval);
          setIsProcessing(false);

          // For a real implementation, this would apply mesh decimation and optimization
          // For now, we're just returning the original mesh
          resolve({
            ...mesh,
            id: mesh.id,
            name: mesh.name,
            createdAt: mesh.createdAt,
          });
        }
      }, 100);
    });
  };

  return {
    isProcessing,
    progress,
    exportFormat,
    saveMeshToLibrary,
    exportMesh,
    shareMesh,
    optimizeMesh,
    setExportFormat,
  };
}
